//! @generated by `diesel-cli`
//!
//! This file is automatically generated by the Diesel CLI.
//! It defines the database schema and should not be modified manually.
//! To update this file, run `diesel migration run` and `diesel print-schema`.

diesel::table! {
    aircraft (id) {
        id -> Integer,
        manufacturer -> Text,
        variant -> Text,
        icao_code -> Text,
        flown -> Integer,
        aircraft_range -> Integer,
        category -> Text,
        cruise_speed -> Integer,
        date_flown -> Nullable<Text>,
        takeoff_distance -> Nullable<Integer>,
    }
}

diesel::table! {
    history (id) {
        id -> Integer,
        departure_icao -> Text,
        arrival_icao -> Text,
        aircraft -> Integer,
        date -> Text,
        distance -> Nullable<Integer>,
    }
}

diesel::table! {
    #[allow(non_snake_case)]
    #[allow(clippy::upper_case_acronyms)]
    Airports (ID) {
        ID -> Integer,
        Name -> Text,
        ICAO -> Text,
        PrimaryID -> Nullable<Integer>,
        Latitude -> Double,
        Longtitude -> Double,
        Elevation -> Integer,
        TransitionAltitude -> Nullable<Integer>,
        TransitionLevel -> Nullable<Integer>,
        SpeedLimit -> Nullable<Integer>,
        SpeedLimitAltitude -> Nullable<Integer>,
    }
}

diesel::table! {
    #[allow(non_snake_case)]
    Runways (ID) {
        ID -> Integer,
        AirportID -> Integer,
        Ident -> Text,
        TrueHeading -> Double,
        Length -> Integer,
        Width -> Integer,
        Surface -> Text,
        Latitude -> Double,
        Longtitude -> Double,
        Elevation -> Integer,
    }
}

diesel::table! {
    metar_cache (station) {
        station -> Text,
        raw -> Text,
        flight_rules -> Nullable<Text>,
        observation_time -> Nullable<Text>,
        observation_dt -> Nullable<Text>,
        fetched_at -> Text,
    }
}

diesel::table! {
    settings (key) {
        key -> Text,
        value -> Text,
    }
}

diesel::allow_tables_to_appear_in_same_query!(aircraft, history, metar_cache, settings,);
